# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# /* wallust template - colors-kitty */

foreground         #EEEFF0
background         #18181A
cursor             #90929B

active_tab_foreground     #18181A
active_tab_background     #EEEFF0
inactive_tab_foreground   #EEEFF0
inactive_tab_background   #18181A

active_border_color   #EEEFF0
inactive_border_color #18181A
bell_border_color     #111119

color0      #3F3F41
color1		#111119
color2		#262834
color3		#646779
color4		#656779
color5		#A86B7C
color6		#9B9CA0
color7		#DEDFE2
color8		#9B9C9E
color9		#171721
color10		#333545
color11		#8689A1
color12		#8689A1
color13		#E08FA6
color14		#CED0D5
color15		#DEDFE2
