# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# /* wallust template - colors-kitty */

foreground         #E2DEDC
background         #151413
cursor             #B9ADA6

active_tab_foreground     #151413
active_tab_background     #E2DEDC
inactive_tab_foreground   #E2DEDC
inactive_tab_background   #151413

active_border_color   #E2DEDC
inactive_border_color #151413
bell_border_color     #4B372B

color0      #3D3B3B
color1		#4B372B
color2		#6B5C54
color3		#827973
color4		#827973
color5		#827973
color6		#827973
color7		#CEC8C4
color8		#908C89
color9		#644939
color10		#8F7B70
color11		#ADA19A
color12		#ADA19A
color13		#ADA19A
color14		#ADA19A
color15		#CEC8C4
