# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# /* wallust template - colors-kitty */

foreground         #EEEEEE
background         #000001
cursor             #98989A

active_tab_foreground     #000001
active_tab_background     #EEEEEE
inactive_tab_foreground   #EEEEEE
inactive_tab_background   #000001

active_border_color   #EEEEEE
inactive_border_color #000001
bell_border_color     #2E2F32

color0      #000001
color1		#2E2F32
color2		#313134
color3		#595758
color4		#5C5A5B
color5		#9F5387
color6		#9A9B9B
color7		#DEDFDE
color8		#9B9C9B
color9		#3E3E42
color10		#424245
color11		#777476
color12		#7B7879
color13		#D46FB4
color14		#CECFCE
color15		#DEDFDE
