# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(000001)
$foreground = rgb(EEEEEE)
$color0 = rgb(000001)
$color1 = rgb(2E2F32)
$color2 = rgb(313134)
$color3 = rgb(595758)
$color4 = rgb(5C5A5B)
$color5 = rgb(9F5387)
$color6 = rgb(9A9B9B)
$color7 = rgb(DEDFDE)
$color8 = rgb(9B9C9B)
$color9 = rgb(3E3E42)
$color10 = rgb(424245)
$color11 = rgb(777476)
$color12 = rgb(7B7879)
$color13 = rgb(D46FB4)
$color14 = rgb(CECFCE)
$color15 = rgb(DEDFDE)
