# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(18181A)
$foreground = rgb(EEEFF0)
$color0 = rgb(3F3F41)
$color1 = rgb(111119)
$color2 = rgb(262834)
$color3 = rgb(646779)
$color4 = rgb(656779)
$color5 = rgb(A86B7C)
$color6 = rgb(9B9CA0)
$color7 = rgb(DEDFE2)
$color8 = rgb(9B9C9E)
$color9 = rgb(171721)
$color10 = rgb(333545)
$color11 = rgb(8689A1)
$color12 = rgb(8689A1)
$color13 = rgb(E08FA6)
$color14 = rgb(CED0D5)
$color15 = rgb(DEDFE2)
