# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(1F1E1E)
$foreground = rgb(DDDBD8)
$color0 = rgb(454444)
$color1 = rgb(292524)
$color2 = rgb(383433)
$color3 = rgb(484441)
$color4 = rgb(57534F)
$color5 = rgb(67625E)
$color6 = rgb(76716C)
$color7 = rgb(C6C3BF)
$color8 = rgb(8B8886)
$color9 = rgb(373130)
$color10 = rgb(4B4643)
$color11 = rgb(605A57)
$color12 = rgb(756E6A)
$color13 = rgb(89837D)
$color14 = rgb(9E9790)
$color15 = rgb(C6C3BF)
